#!/usr/bin/python3
import sys


def gcd(a, b):
    while b:
        a, b = b, a % b
    return a

def pollard_rho(n):
    if n % 2 == 0:
        print("{}={}*{}".format(n, n // 2, 2))
        return
    x = 2
    y = 2
    d = 1

    while d == 1:
        x = (x * x + 1) % n
        y = (y * y + 1) % n
        y = (y * y + 1) % n
        d = gcd(abs(x - y), n)
    print("{}={}*{}".format(n, d, n // d))

with open(sys.argv[1], 'r') as file:
    for line in file.readlines():
        pollard_rho(int(line))
